import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/Layout/Provider";
import { getServerSession } from "next-auth";
import authOptions from "@/lib/authOptions";
import {Roboto} from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Robot = Roboto({
  weight:['100','200','300','400','500','600','700'],
  style: "normal",
  subsets: ['latin'],
  variable: "--roboto"
})
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
      className={Robot.className}
     
      >
       <Provider session ={session}>
         {children}
       </Provider>
      </body>
    </html>
  );
}
